export const BLACK_HOLE_RENDER_PROFILE = Object.freeze({
  maxDpr: 1.35,
  visibleMeshCount: 5,
  visibleObjectCount: 6,
  eventHorizon: Object.freeze({
    radius: 2.7,
    widthSegments: 48,
    heightSegments: 32,
  }),
  hotDisk: Object.freeze({
    innerRadius: 2.88,
    outerRadius: 5.1,
    fadeStart: 4.6,
    angularSegments: 160,
    radialSegments: 7,
    period: 36,
    layer: 0,
    verticalOffset: 0.008,
  }),
  dustDisk: Object.freeze({
    innerRadius: 3.85,
    outerRadius: 7.7,
    fadeStart: 7,
    angularSegments: 160,
    radialSegments: 7,
    period: 74,
    layer: 1,
    verticalOffset: -0.008,
  }),
  lensShell: Object.freeze({
    radius: 2.84,
    scaleY: 1.12,
    widthSegments: 72,
    heightSegments: 36,
  }),
  fallbackDisk: Object.freeze({
    innerRadius: 2.88,
    outerRadius: 7.7,
    angularSegments: 96,
    opacity: 0.08,
  }),
  halo: Object.freeze({
    innerRadius: 7.5,
    outerRadius: 17.5,
    size: 0.12,
    opacity: 0.5,
  }),
  doppler: Object.freeze({ minimum: 0.52, maximum: 1.62 }),
  palette: Object.freeze({
    inner: '#fff8e8',
    mid: '#dfb77d',
    outer: '#684633',
    rim: '#f0d9bd',
  }),
})
